config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#root'
  get 'index' => 'static_pages#index', defaults: { format: :html }
  get 'shared/:id' => 'shared_notes#shared', defaults: { format: :html }

  resource :user, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :notebooks, except: [:new, :edit]
    resources :notes, except: [:new, :edit] do
      get 'search', on: :collection
    end
    resources :tags, only: [:index, :show, :destroy] do
      get 'search', on: :collection
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_login, only: :root

  def index
    if current_user
      redirect_to root_url
    end
  end

  def root
  end
end

app/views/static_pages/_sidebar.html.erb
<ul class="sidebar__list clearfix">
  <a href='#'>
    <li class="sidebar__list__item--logo">
      <div class="sidebar__img--logo"> </div>
      <div class="sidebar__list__item__text"> QuiqNote </div>
    </li>
  </a>

  <a href='#/notes/new'>
    <li class="sidebar__list__item--new-note">
      <div class="sidebar__img--new-note"> </div>
      <div class="sidebar__list__item__text"> NEW NOTE </div>
    </li>
  </a>

  <a href='#/search'>
    <li class="sidebar__list__item--search">
      <div class="sidebar__img--search"> </div>
      <div class="sidebar__list__item__text"> SEARCH </div>
    </li>
  </a>

  <a href='#'>
    <li class="sidebar__list__item--notes">
      <div class="sidebar__img--notes"> </div>
      <div class="sidebar__list__item__text"> NOTES </div>
    </li>
  </a>

  <a href='#/notebooks'>
    <li class="sidebar__list__item--notebooks">
      <div class="sidebar__img--notebooks"> </div>
      <div class="sidebar__list__item__text"> NOTEBOOKS </div>
    </li>
  </a>

  <a href='#/shortcuts'>
    <li class="sidebar__list__item--shortcuts">
      <div class="sidebar__img--shortcuts"> </div>
      <div class="sidebar__list__item__text"> SHORTCUTS </div>
    </li>
  </a>

  <a href='#/tags'>
    <li class="sidebar__list__item--tags">
      <div class="sidebar__img--tags"> </div>
      <div class="sidebar__list__item__text"> TAGS </div>
    </li>
  </a>


  <li class="sidebar__list__item--log-out">
    <div class="sidebar__logout">
      <%= button_to 'log out', session_url, method: :delete %>
    </div>
  </li>
</ul>

app/views/static_pages/index.html.erb
<!-- Navigation -->

<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
    <div class="container topnav">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" href="#top">QuiqNote</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#about">Features</a>
                </li>
                <li>
                    <a href="<%= new_session_url %>">Sign in</a>
                </li>
                <li>
                    <a href="<%= new_user_url %>">Sign up</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>


<!-- Header -->
<div class="intro-header" id="top">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>QuiqNote</h1>
                    <h3>A notes app inspired by Evernote</h3>
                    <hr class="intro-divider">
                    <ul class="list-inline intro-social-buttons">
                        <li>
                            <a href="<%= new_user_url %>" class="btn btn-lg custom-button"><span class="network-name">Sign up</span></a>
                        </li>
                        <li>
                            <a href="<%= new_session_url %>" class="btn btn-lg custom-button"><span class="network-name">Sign in</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-lg custom-button guest-login"><span class="network-name">Guest Login</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.intro-header -->

<!-- Page Content -->

<a  name="about"></a>
<div class="content-section-a">

    <div class="container">
        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Support for rich formats</h2>
                <p class="lead">All the text-editing features that you'd expect. Customize the font, add colors, lists, images and links.</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag 'editor.jpg', class: 'img-responsive' %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->

<div class="content-section-b">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Organize and easily find your notes.</h2>
                <p class="lead">Notebooks, tags, and shortcuts allow you to organize your notes the way you want to. The search feature helps you find what you need quickly.</p>
            </div>
            <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                <%= image_tag 'organize.jpg', class: 'img-responsive' %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-b -->

<div class="content-section-a">

    <div class="container">

        <div class="row">
            <div class="col-lg-5 col-sm-6">
                <hr class="section-heading-spacer">
                <div class="clearfix"></div>
                <h2 class="section-heading">Share notes</h2>
                <p class="lead">Easily share your notes with someone else via a unique URL.</p>
            </div>
            <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                <%= image_tag 'share_note_big.png', class: 'img-responsive' %>
            </div>
        </div>

    </div>
    <!-- /.container -->

</div>
<!-- /.content-section-a -->
</div>
<form class="guest_hidden" action="/session" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
         <input id="user_password" type="password" name="user[password]" value="quiqnote">
         <input id="user_email"
                type="text"
                name="user[email]"
                value="guest@quiqnote.com">
</form>

<script>
  $(document).ready(function() {
    $(".guest-login").click(function(event) {
      $("form.guest_hidden").submit();
    })
    // smooth scrolling
    $('a[href*=#]:not([href=#])').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top
          }, 800);
          return false;
        }
      }
    });
  });
</script>

app/views/static_pages/root.html.erb
  <div id="main" class="full-height">
    <!-- <div class="nav navbar sidebar-padding"> -->
      <nav id="sidebar" class="navbar">
          <%= render partial: 'sidebar' %>
      </nav>
      <div id="content" class="container sidebar-padding">
      </div>
    <!-- </div> -->
  </div>